src/inventory/urls.py
from django.urls import path
from inventory.views import add_material_view, get_all_materials, get_material_details


app_name = 'inventory'


urlpatterns = [
    path('add-material/', add_material_view, name='add_material'),
    path('get-all-materials/', get_all_materials, name='get_materials'),
    path('get-material/<int:material_id>/', get_material_details, name='material_details'),
]

src/stocks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inventory/', include('inventory.urls', namespace='inventory')),
    path("auth/", include('users.urls', namespace="auth")),
    path('', lambda request: render(request, 'home.html'), name='home')
]

src/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import register_view, profile_view


app_name = 'auth'

urlpatterns = [
    path("register/", register_view, name="register"),
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", profile_view, name="profile_view")
]

src/inventory/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxLengthValidator


class Material(models.Model):
    class Unit(models.TextChoices):
        LITRE = 'l', 'litre'
        KILOGRAM = 'kg', 'kilogram'
        M2 = 'm2', 'm²'
        PIECE = 'pcs', 'piece'
        PACK = 'pack', 'pack'
    name = models.CharField(max_length=64)
    unit_price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(0)])
    unit = models.CharField(max_length=10, choices=Unit.choices)
    quantity = models.DecimalField(max_digits=10, decimal_places=2, default=0)


    def __str__(self):
        return self.name

src/users/models.py
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models

class CustomUserManager(BaseUserManager):
    def create_user(self, email, password, **extra_fields):
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password) # password hashing
        user.save()
        return user
    
    def create_superuser(self, email, password, **extra_fields):
        user = self.create_user(email, password, **extra_fields)
        user.is_active = True
        user.is_staff = True
        user.is_superuser = True
        user.save()
        return user


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    name = models.CharField(max_length=128)
    surname = models.CharField(max_length=128)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = "email"
    EMAIL_FIELD = "email"
    REQUIRED_FIELDS = ["name", "surname"]

    objects = CustomUserManager()

    def __str__(self):
        return self.email

src/inventory/forms.py
from django import forms
from .models import Material

class MaterialForm(forms.ModelForm):
    class Meta:
        model = Material
        fields = ['name', 'unit_price', 'unit', 'quantity']
        labels = {
            "name": ("Material"),
        }
        help_texts = {
            "name": ("The title of material"),
            "quantity": ("Total quantity of units"),
            "unit_price": ("Price per unit of product")
        }

src/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser


class RegistrationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("name", "surname", "email", "password1", "password2")

    def save(self, commit=True): # default value
        user = super().save(commit=False)
        user.is_active = True
        user.save()
        return user

src/inventory/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages

from .forms import MaterialForm
from .models import Material

def add_material_view(request):
    if request.method == "POST":
        form = MaterialForm(request.POST)
        if form.is_valid():
            material = form.save(commit=False)
            material.save()
            messages.success(request, "Material has been created")
            return redirect("inventory:add_material") 
    form = MaterialForm()
    return render(request, "inventory/add_material.html", {"form": form})


def get_all_materials(request):
    materials = Material.objects.all()
    return render(request, "inventory/get_materials.html", {"materials": materials})


def get_material_details(request, material_id):
    material = get_object_or_404(Material, id=material_id)
    return render(request, "inventory/material_details.html", {"material": material})

src/users/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .forms import RegistrationForm


def register_view(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("inventory:get_materials")
    form = RegistrationForm()
    return render(request, "users/register.html", {"form": form})


@login_required
def profile_view(request):
    return render(request, "users/profile.html")

src/inventory/templates/inventory/add_material.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h1>Add a material</h1>
<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Add</button>
</form>

{% endblock %}

src/inventory/templates/inventory/get_materials.html
{% extends 'base.html' %}

{% block content %}
<h2>All materials:</h2>
{% load inventory_tags %}

{% get_materials %}

{% endblock %}

src/inventory/templates/inventory/material_details.html
{% extends 'base.html' %}

{% block content %}
<h2>{{ material.name }}</h2>
<p>Unit price: {{ material.unit_price }}</p>
<p>Quantity: {{ material.quantity }} {{ material.unit }}</p>

<a href="{% url 'inventory:get_materials' %}">Back to all materials</a>
{% endblock %}

src/inventory/templates/inventory/materials_list.html
<ul>
    {% for m in materials %}
    <li>
        <a href="{% url 'inventory:material_details' m.id %}">{{m.name}}</a>
    </li>
    {% endfor %}
</ul>

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My Site{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
    crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'inventory:get_materials' %}">Materials</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'inventory:add_material' %}">Add a material</a>
        </li>
        <li class="nav-item dropdown active">
          <a class="nav-link active dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Auth
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'auth:register' %}">Sign up</a></li>
            <li><a class="dropdown-item" href="{% url 'auth:login' %}">Log in</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

{% if messages %}
<div class="container mt-3">
    {% for message in messages %}
    <div class="alert alert-{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}danger{% else %}success{% endif %} alert-dismissible fade show"
        role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
</div>
{% endif %}
    {% block content %}

    {% endblock %}
<script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous">
  </script>
</body>
</html>

src/templates/home.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<h1 style="color: blue;">Welcome to my site!</h1>

{% endblock %}

src/users/templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-5" style="max-width: 400px;">
  <h2 class="mb-4">Login</h2>

  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <button type="submit" class="btn btn-primary">Login</button>
  </form>

  <p class="mt-3">
    Don’t have an account? <a href="{% url 'auth:register' %}">Register here</a>
  </p>
</div>
{% endblock %}

src/users/templates/users/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-5">
  <h1> Welcome, {{ user.name }} {{ user.surname }}</h1>
  <p> Email: {{ user.email }}</p>
  <p> You're logged in successfully! </p>
</div>
{% endblock %}

src/users/templates/users/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
  <div class="col-md-6">
    <h2 class="mb-4 text-center">Register</h2>
    <form method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary w-100 mt-3 mb-5">Register</button>
    </form>
  </div>
</div>
{% endblock %}